#shapes
print('building shapes')
import example.shape.arch_round
import example.shape.arch
import example.shape.arrow
import example.shape.backdrop
import example.shape.chevron
import example.shape.coffin
import example.shape.cone
import example.shape.cornerJoin
import example.shape.coffin
import example.shape.crescent
import example.shape.cross
import example.shape.cube
import example.shape.cylinder
import example.shape.cylinder_sector
import example.shape.diamond
import example.shape.ellipse_sector
import example.shape.heptagon
import example.shape.hexagon
import example.shape.iBeam
import example.shape.jersey_barrier
import example.shape.lightning
import example.shape.nonagon
import example.shape.octagon
import example.shape.pentagon
import example.shape.pinwheel
import example.shape.pipe
import example.shape.pyramid
import example.shape.rail
import example.shape.rhombus
import example.shape.ring
import example.shape.sphere
import example.shape.star_sweep
import example.shape.star
import example.shape.trapezoid
import example.shape.triangle
import example.shape.triangle_right
import example.shape.triangle_isosceles
import example.shape.vase
import example.shape.teardrop
import example.shape.step_pyramid

# waves
print('building waves')
import example.wave.sawtooth_sweep
import example.wave.sawtooth
import example.wave.sine
import example.wave.square_twist_extrude
import example.wave.square_twist_extrude2
import example.wave.square
import example.wave.triangle
import example.wave.uneven
import example.wave.uneven_grid
import example.wave.uneven_spline
import example.wave.uneven_spline_grid

print('building hinges')
import example.hinge.hinge
import example.hinge.hinge_larger_tab
import example.hinge.hinge_render
import example.hinge.hinge_invert
import example.hinge.simple_door
import example.hinge.simple_frame
import example.hinge.simple_pivot
import example.hinge.simple_hinge

print('building grids')
import example.grid.cell_single
import example.grid.exampleGrid
import example.grid.grid_arc_points
import example.grid.grid_arc_points_coords
import example.grid.grid_arc_points_random
import example.grid.grid_cell_basic
import example.grid.grid_cell_random
import example.grid.grid_cell_basic_arc
import example.grid.grid_cell_basic_arc_random
import example.grid.grid_cell_basic_mod
import example.grid.grid_cell_basic_random
import example.grid.grid_points
import example.grid.grid_points_coords
import example.grid.grid_points_mod
import example.grid.grid_points_random
import example.grid.grid_points_random_coords
import example.grid.hexagonGrid
import example.grid.irregularGrid_hardCoded
import example.grid.irregularGrid
import example.grid.join_cells_interlock
import example.grid.points_randomize
import example.grid.randomized_rotation_grid
import example.grid.rotate_grid
import example.grid.series
import example.grid.seriesOperation
import example.grid.starGrid

print("helper plate")
import example.helper_plate