#shapes
print('building shapes')
import example.shape.arch_round
import example.shape.arch
import example.shape.arrow
import example.shape.backdrop
import example.shape.chevron
import example.shape.coffin
import example.shape.cone
import example.shape.cornerJoin
import example.shape.coffin
import example.shape.crescent
import example.shape.cross
import example.shape.cube
import example.shape.cylinder
import example.shape.cylinder_sector
import example.shape.diamond
import example.shape.ellipse_sector
import example.shape.heptagon
import example.shape.hexagon
import example.shape.iBeam
import example.shape.jersey_barrier
import example.shape.lightning
import example.shape.nonagon
import example.shape.octagon
import example.shape.pentagon
import example.shape.pinwheel
import example.shape.pipe
import example.shape.pyramid
import example.shape.rail
import example.shape.rhombus
import example.shape.ring
import example.shape.sphere
import example.shape.star_sweep
import example.shape.star
import example.shape.trapezoid
import example.shape.triangle
import example.shape.triangle_right
import example.shape.triangle_isosceles
import example.shape.vase
import example.shape.teardrop
import example.shape.step_pyramid

# waves
print('building waves')
import example.wave.sawtooth_sweep
import example.wave.sawtooth
import example.wave.sine
import example.wave.square_twist_extrude
import example.wave.square_twist_extrude2
import example.wave.square
import example.wave.triangle
import example.wave.uneven
import example.wave.uneven_grid
import example.wave.uneven_spline
import example.wave.uneven_spline_grid

print('building hinges')
import example.hinge
import example.hinge_larger_tab
import example.hinge_render
import example.hinge_invert

print('building grids')
import example.exampleGrid
import example.hexagonGrid
import example.irregularGrid_hardCoded
import example.irregularGrid
import example.series
import example.seriesOperation
import example.starGrid

print("helper plate")
import example.helper_plate